# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/polit/Documents/n10489045, N10485571  - FIR Filter Vivado and bit file/06_demo_all_2021/src_ip/mem_oled_char_lib/mem_oled_char_lib.xci
# IP: The module: 'mem_oled_char_lib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/polit/Documents/n10489045, N10485571  - FIR Filter Vivado and bit file/06_demo_all_2021/src_ip/mem_oled_char_lib/mem_oled_char_lib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_oled_char_lib'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/polit/Documents/n10489045, N10485571  - FIR Filter Vivado and bit file/06_demo_all_2021/src_ip/mem_oled_char_lib/mem_oled_char_lib.xci
# IP: The module: 'mem_oled_char_lib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/polit/Documents/n10489045, N10485571  - FIR Filter Vivado and bit file/06_demo_all_2021/src_ip/mem_oled_char_lib/mem_oled_char_lib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_oled_char_lib'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
